---
roles:
  - name: composer
    src: geerlingguy.composer
    version: 1.9.0

  - name: ntp
    src: geerlingguy.ntp
    version: 2.3.1

  - name: logrotate
    src: nickhammond.logrotate
    version: v0.0.5

  - name: swapfile
    src: oefenweb.swapfile
    version: v2.0.36

  - name: mailpit
    src: roots.mailpit
    version: v1.0.0

  - name: wordfence
    src: adleviton.trellis_wordfence

  - name: do-agent
    src: andrewsomething.do-agent
    version: v1.1.1
