#php_error_reporting: 'E_ALL'
#php_display_errors: 'On'
#php_display_startup_errors: 'On'
#php_mysqlnd_collect_memory_statistics: 'On'
#php_opcache_enable: 0

#xdebug_mode: 'debug'
#xdebug_start_with_request: 'yes'
#xdebug_discover_client_host: 1

# Fast start defaults
php_error_reporting: 'E_ALL ^ E_DEPRECATED'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_mysqlnd_collect_memory_statistics: 'Off'
php_opcache_enable: 1

xdebug_mode: 'develop'
xdebug_start_with_request: 'no'
xdebug_discover_client_host: 0
